
services:
  lsa:
    container_name: lsa
    build:
      context: .
      dockerfile: Dockerfile.lsa   # добавим на шаге 2
    ports:
      - "8876:8766"
    environment:
      PYTHONUNBUFFERED: "1"
      TESSDATA_PREFIX: "/usr/share/tesseract-ocr/5/tessdata"
    volumes:
      - ./:/app:rw
      - ./logs:/app/logs
    working_dir: /app
    command: ["bash","-lc","./scripts/run_api.sh"]  # добавим на шаге 3
    restart: unless-stopped
