name: release
on:
  push:
    tags: ["v*.*.*"]
permissions:
  contents: read
  packages: write
jobs:
  task_api_image:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: docker/setup-buildx-action@v3
      - uses: docker/login-action@v3
        with:
          registry: ghcr.io
          username: ${{ github.actor }}
          password: ${{ secrets.GITHUB_TOKEN }}
      - uses: docker/build-push-action@v6
        with:
          context: .
          file: ./deploy/Dockerfile.task_api
          push: true
          tags: ghcr.io/${{ github.repository }}/task-api:${{ github.ref_name }}
